"""
embed_mazes.py — Reads all maze .txt files and generates maze_data.js
for the Maze Solver Visualizer.

Output format:
  const MAZE_DB = [
    { n:"maze0_dim42", t:"p", d:42, r:85, c:85, m:"base64..." },
    ...
  ];

Each maze is packed: 8 cells per byte, then base64-encoded.
"""

import os
import base64
import json
import time

PROJECT_ROOT = os.path.dirname(os.path.dirname(__file__))
PERFECT_DIR = os.path.join(PROJECT_ROOT, 'data', 'raw', 'perfect_maze')
IMPERFECT_DIR = os.path.join(PROJECT_ROOT, 'data', 'raw', 'imperfect_maze')
OUTPUT_FILE = os.path.join(PROJECT_ROOT, 'data', 'processed', 'maze_data.js')
SAMPLE_FILE = os.path.join(PROJECT_ROOT, 'data', 'processed', 'maze_data_sample.js')


def parse_maze_file(filepath):
    """Read a maze .txt file and return the grid as list of lists of int."""
    with open(filepath, 'r') as f:
        lines = f.readlines()
    grid = []
    for line in lines:
        line = line.strip()
        if line:
            grid.append(list(map(int, line.split())))
    return grid


def pack_maze(grid):
    """Pack a 2D grid of 0/1 into base64-encoded bytes (8 bits per byte)."""
    bits = []
    for row in grid:
        bits.extend(row)
    # Pad to multiple of 8
    while len(bits) % 8 != 0:
        bits.append(0)
    # Pack into bytes
    byte_arr = bytearray()
    for i in range(0, len(bits), 8):
        byte_val = 0
        for j in range(8):
            byte_val = (byte_val << 1) | bits[i + j]
        byte_arr.append(byte_val)
    return base64.b64encode(byte_arr).decode('ascii')


def parse_filename(filename):
    """Extract name and dimension from filename like 'maze0_dim42.txt'."""
    name = filename.replace('.txt', '')
    parts = name.split('_')
    dim = int(parts[1].replace('dim', ''))
    return name, dim


def process_directory(directory, maze_type_code):
    """Process all maze files in a directory. Returns list of maze entries."""
    entries = []
    files = sorted([f for f in os.listdir(directory) if f.endswith('.txt')])
    total = len(files)
    
    for idx, filename in enumerate(files):
        filepath = os.path.join(directory, filename)
        name, dim = parse_filename(filename)
        grid = parse_maze_file(filepath)
        rows = len(grid)
        cols = len(grid[0]) if grid else 0
        b64_data = pack_maze(grid)
        
        entries.append({
            'n': name,
            't': maze_type_code,
            'd': dim,
            'r': rows,
            'c': cols,
            'm': b64_data
        })
        
        if (idx + 1) % 100 == 0 or idx == total - 1:
            print(f"  [{maze_type_code.upper()}] {idx + 1}/{total} processed")
    
    return entries


def write_js_file(entries, output_path):
    """Write maze entries to a JS file."""
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by embed_mazes.py\n')
        f.write(f'// Total mazes: {len(entries)}\n')
        f.write(f'// Generated: {time.strftime("%Y-%m-%d %H:%M:%S")}\n')
        f.write('const MAZE_DB = ')
        # Use compact JSON (no indent, no spaces)
        json_str = json.dumps(entries, separators=(',', ':'))
        f.write(json_str)
        f.write(';\n')
    
    file_size = os.path.getsize(output_path)
    return file_size


def main():
    print("=" * 60)
    print("  Maze Data Embedder")
    print("  Reads maze .txt files and generates maze_data.js")
    print("=" * 60)
    
    all_entries = []
    
    # Process perfect mazes
    if os.path.isdir(PERFECT_DIR):
        print(f"\nProcessing perfect mazes from: {PERFECT_DIR}")
        perfect = process_directory(PERFECT_DIR, 'p')
        all_entries.extend(perfect)
        print(f"  => {len(perfect)} perfect mazes processed")
    else:
        print(f"WARNING: Directory not found: {PERFECT_DIR}")
    
    # Process imperfect mazes
    if os.path.isdir(IMPERFECT_DIR):
        print(f"\nProcessing imperfect mazes from: {IMPERFECT_DIR}")
        imperfect = process_directory(IMPERFECT_DIR, 'i')
        all_entries.extend(imperfect)
        print(f"  => {len(imperfect)} imperfect mazes processed")
    else:
        print(f"WARNING: Directory not found: {IMPERFECT_DIR}")
    
    # Sort by type then name
    all_entries.sort(key=lambda e: (e['t'], e['n']))
    
    # Write full data file
    print(f"\nWriting full maze data to: {OUTPUT_FILE}")
    full_size = write_js_file(all_entries, OUTPUT_FILE)
    print(f"  => {len(all_entries)} mazes, file size: {full_size / 1024 / 1024:.2f} MB")
    
    # Write sample file (10 smallest mazes: 5 perfect + 5 imperfect)
    print(f"\nWriting sample data to: {SAMPLE_FILE}")
    perfect_sorted = sorted([e for e in all_entries if e['t'] == 'p'], key=lambda e: e['d'])
    imperfect_sorted = sorted([e for e in all_entries if e['t'] == 'i'], key=lambda e: e['d'])
    sample = perfect_sorted[:5] + imperfect_sorted[:5]
    sample.sort(key=lambda e: (e['t'], e['n']))
    sample_size = write_js_file(sample, SAMPLE_FILE)
    print(f"  => {len(sample)} mazes, file size: {sample_size / 1024:.2f} KB")
    
    # Summary
    print("\n" + "=" * 60)
    print("  DONE!")
    print(f"  Total mazes: {len(all_entries)}")
    dims = [e['d'] for e in all_entries]
    print(f"  Dim range: {min(dims)} - {max(dims)}")
    print(f"  Full file: {full_size / 1024 / 1024:.2f} MB")
    print(f"  Sample file: {sample_size / 1024:.2f} KB")
    print("=" * 60)


if __name__ == '__main__':
    main()
